// DevPulse - Production-Grade Developer Knowledge & Code Review Graph Seed Script
MATCH (n) DETACH DELETE n;

CREATE 
  (d1:Developer {id: "dev_1", name: "Sarah Jenkins", team: "Security & Core API", tenure: "Senior Engineer (4 yrs)", avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80"}),
  (d2:Developer {id: "dev_2", name: "Krishna Chaitu", team: "Backend Architecture", tenure: "Tech Lead (3 yrs)", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80"}),
  (d3:Developer {id: "dev_3", name: "Alex Rivera", team: "Payments & Commerce", tenure: "Senior Backend Dev (2.5 yrs)", avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80"}),
  (d4:Developer {id: "dev_4", name: "Carlos Mendez", team: "Database & Infra", tenure: "Staff Architect (6 yrs)", avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80"}),
  (d5:Developer {id: "dev_5", name: "Emily Watson", team: "Authentication & Identity", tenure: "Security Engineer (2 yrs)", avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80"}),
  (d6:Developer {id: "dev_6", name: "Mike Zhang", team: "Frontend & Integrations", tenure: "Junior Engineer (1 yr)", avatarUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=300&q=80"}),
  (d7:Developer {id: "dev_7", name: "Priya Patel", team: "Cloud & DevOps", tenure: "Principal SRE (5 yrs)", avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80"}),
  (d8:Developer {id: "dev_8", name: "David Kim", team: "API Gateway & Services", tenure: "Staff Engineer (4 yrs)", avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80"}),
  (d9:Developer {id: "dev_9", name: "Hannah Abbott", team: "Data & Analytics", tenure: "Senior Data Engineer (3 yrs)", avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80"}),
  (d10:Developer {id: "dev_10", name: "Lucas Vance", team: "Platform & Performance", tenure: "Principal Engineer (7 yrs)", avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80"}),

  (r1:Repository {id: "repo_1", name: "payment-gateway-service", language: "Java"}),
  (r2:Repository {id: "repo_2", name: "auth-identity-service", language: "Java"}),
  (r3:Repository {id: "repo_3", name: "core-api-service", language: "Java"}),
  (r4:Repository {id: "repo_4", name: "infrastructure-config", language: "HCL"}),
  (r5:Repository {id: "repo_5", name: "data-analytics-pipeline", language: "Python"}),

  (f1:File {id: "file_1", path: "OrderService.java", extension: "java", linesOfCode: 450}),
  (f2:File {id: "file_2", path: "PaymentGateway.java", extension: "java", linesOfCode: 620}),
  (f3:File {id: "file_3", path: "AuthCore.java", extension: "java", linesOfCode: 890}),
  (f4:File {id: "file_4", path: "TokenValidator.java", extension: "java", linesOfCode: 310}),
  (f5:File {id: "file_5", path: "V2__payment_schema.sql", extension: "sql", linesOfCode: 120}),
  (f6:File {id: "file_6", path: "CheckoutController.java", extension: "java", linesOfCode: 280}),
  (f7:File {id: "file_7", path: "StripeClient.java", extension: "java", linesOfCode: 510}),
  (f8:File {id: "file_8", path: "JWTUtils.java", extension: "java", linesOfCode: 340}),
  (f9:File {id: "file_9", path: "AuditLogger.java", extension: "java", linesOfCode: 230}),
  (f10:File {id: "file_10", path: "SecurityConfig.java", extension: "java", linesOfCode: 410}),
  (f11:File {id: "file_11", path: "RateLimiter.java", extension: "java", linesOfCode: 290}),
  (f12:File {id: "file_12", path: "DatabasePoolConfig.java", extension: "java", linesOfCode: 180}),

  (t1:Tag {id: "tag_1", name: "Security", category: "Domain"}),
  (t2:Tag {id: "tag_2", name: "Payments", category: "Domain"}),
  (t3:Tag {id: "tag_3", name: "Database", category: "Infra"}),
  (t4:Tag {id: "tag_4", name: "Auth", category: "Security"}),
  (t5:Tag {id: "tag_5", name: "Performance", category: "Optimization"}),
  (t6:Tag {id: "tag_6", name: "DevOps", category: "Infra"}),

  (pr45:PullRequest {id: "pr_45", prNumber: 45, title: "Refactor OrderService payment flow", status: "MERGED", createdAt: "2026-08-10T10:00:00Z"}),
  (pr88:PullRequest {id: "pr_88", prNumber: 88, title: "Integrate Stripe v2 in PaymentGateway", status: "MERGED", createdAt: "2026-08-12T14:30:00Z"}),
  (pr102:PullRequest {id: "pr_102", prNumber: 102, title: "Harden AuthCore JWT token validation", status: "MERGED", createdAt: "2026-08-14T09:15:00Z"}),
  (pr105:PullRequest {id: "pr_105", prNumber: 105, title: "Optimize V2 payment database indices", status: "MERGED", createdAt: "2026-08-15T11:20:00Z"}),
  (pr112:PullRequest {id: "pr_112", prNumber: 112, title: "Add CheckoutController rate limiting", status: "OPEN", createdAt: "2026-08-16T16:00:00Z"}),
  (pr120:PullRequest {id: "pr_120", prNumber: 120, title: "Upgrade Stripe SDK to 2026 spec", status: "MERGED", createdAt: "2026-08-17T08:45:00Z"}),
  (pr125:PullRequest {id: "pr_125", prNumber: 125, title: "Add SecurityConfig CSRF & OAuth2 rules", status: "MERGED", createdAt: "2026-08-18T13:10:00Z"}),
  (pr130:PullRequest {id: "pr_130", prNumber: 130, title: "Tune DatabasePoolConfig HikariCP settings", status: "OPEN", createdAt: "2026-08-19T07:00:00Z"}),

  (f1)-[:DEPENDS_ON {type: "IMPORT"}]->(f2),
  (f6)-[:DEPENDS_ON {type: "CALLS"}]->(f1),
  (f2)-[:DEPENDS_ON {type: "AUTHENTICATES_VIA"}]->(f3),
  (f2)-[:DEPENDS_ON {type: "DELEGATES_TO"}]->(f7),
  (f3)-[:DEPENDS_ON {type: "USES"}]->(f4),
  (f3)-[:DEPENDS_ON {type: "USES"}]->(f8),
  (f2)-[:DEPENDS_ON {type: "PERSISTS_VIA"}]->(f5),
  (f10)-[:DEPENDS_ON {type: "CONFIGURES"}]->(f3),
  (f6)-[:DEPENDS_ON {type: "PROTECTED_BY"}]->(f11),
  (f5)-[:DEPENDS_ON {type: "MANAGED_BY"}]->(f12),
  (f3)-[:DEPENDS_ON {type: "AUDITS_TO"}]->(f9),

  (pr45)-[:CHANGES {additions: 150}]->(f1),
  (pr88)-[:CHANGES {additions: 320}]->(f2),
  (pr102)-[:CHANGES {additions: 210}]->(f3),
  (pr102)-[:CHANGES {additions: 90}]->(f4),
  (pr105)-[:CHANGES {additions: 45}]->(f5),
  (pr112)-[:CHANGES {additions: 110}]->(f6),
  (pr120)-[:CHANGES {additions: 240}]->(f7),
  (pr125)-[:CHANGES {additions: 180}]->(f10),
  (pr130)-[:CHANGES {additions: 65}]->(f12),

  (pr45)-[:TAGGED_WITH]->(t2),
  (pr88)-[:TAGGED_WITH]->(t2),
  (pr102)-[:TAGGED_WITH]->(t1),
  (pr102)-[:TAGGED_WITH]->(t4),
  (pr105)-[:TAGGED_WITH]->(t3),
  (pr112)-[:TAGGED_WITH]->(t5),
  (pr125)-[:TAGGED_WITH]->(t1),
  (pr130)-[:TAGGED_WITH]->(t3),

  (d3)-[:CREATED]->(pr45),
  (d3)-[:CREATED]->(pr88),
  (d5)-[:CREATED]->(pr102),
  (d4)-[:CREATED]->(pr105),
  (d6)-[:CREATED]->(pr112),
  (d3)-[:CREATED]->(pr120),
  (d1)-[:CREATED]->(pr125),
  (d7)-[:CREATED]->(pr130),

  (d1)-[:REVIEWED {score: 95, thoroughness: "HIGH"}]->(pr45),
  (d2)-[:REVIEWED {score: 90, thoroughness: "HIGH"}]->(pr88),
  (d1)-[:REVIEWED {score: 98, thoroughness: "CRITICAL"}]->(pr88),
  (d2)-[:REVIEWED {score: 92, thoroughness: "HIGH"}]->(pr102),
  (d4)-[:REVIEWED {score: 85, thoroughness: "MEDIUM"}]->(pr102),
  (d2)-[:REVIEWED {score: 88, thoroughness: "HIGH"}]->(pr105),
  (d3)-[:REVIEWED {score: 75, thoroughness: "MEDIUM"}]->(pr112),
  (d2)-[:REVIEWED {score: 94, thoroughness: "HIGH"}]->(pr120),
  (d5)-[:REVIEWED {score: 96, thoroughness: "CRITICAL"}]->(pr125),
  (d4)-[:REVIEWED {score: 91, thoroughness: "HIGH"}]->(pr130),

  (d2)-[:FOLLOWS]->(d1),
  (d1)-[:FOLLOWS]->(d4),
  (d4)-[:FOLLOWS]->(d10),
  (d6)-[:FOLLOWS]->(d3),
  (d3)-[:FOLLOWS]->(d2),
  (d5)-[:FOLLOWS]->(d1),
  (d8)-[:FOLLOWS]->(d2),
  (d7)-[:FOLLOWS]->(d4),
  (d9)-[:FOLLOWS]->(d2);
