spring.application.name=devpulse

# Server Port Setting (Supports dynamic Cloud Hosting PORT variable)
server.port=${PORT:8080}

# CognoDB Cloud Connection Settings
spring.neo4j.uri=${NEO4J_URI:bolt+s://db-7ba26f4a.databases.cognodb.com:7687}
spring.neo4j.authentication.username=${NEO4J_USERNAME:cognodb}
spring.neo4j.authentication.password=${NEO4J_PASSWORD:998ebf2bc471a0bf18d308e58fb94526}

# TLS/SSL Encryption Trust Strategy
spring.neo4j.security.trust-strategy=TRUST_ALL_CERTIFICATES

# Keep-Alive & Connection Pool Resilience Settings
spring.neo4j.pool.max-connection-lifetime=15m
spring.neo4j.pool.idle-time-before-connection-test=1s
spring.neo4j.pool.connection-acquisition-timeout=30s
spring.neo4j.pool.max-connection-pool-size=50
