spring.application.name=devpulse

# CognoDB Cloud / Neo4j Database Connection
spring.neo4j.uri=${NEO4J_URI:bolt+s://db-7ba26f4a.databases.cognodb.com}
spring.neo4j.authentication.username=${NEO4J_USERNAME:cognodb}
spring.neo4j.authentication.password=${NEO4J_PASSWORD:998ebf2bc471a0bf18d308e58fb94526}
